#!/bin/bash
cd /var/www/phplaravel
yum -y update
yum -y install nginx php71 php71-devel php71-mysqlnd php71-pdo php71-mbstring php71-mcrypt
curl -s https://getcomposer.org/installer | php
php composer.phar install
mv composer.phar /usr/local/bin/composer
cp .env.example .env
chown -R ec2-user:ec2-user /var/www/phplaravel
userAdd -G ec2-user nginx
chgrp -R nginx storage bootstrap/cache
chmod -R ug+rwx storage bootstrap/cache
